<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SL-1155.attlocal.net" failures="55" tests="108" name="Command line test" time="393.25" errors="0" timestamp="14 Feb 2019 20:03:23 GMT">
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="23.253"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="25.567"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="29.553">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.Login(WebDemoTest.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="40.525"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="17.62">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="18.705">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="18.916">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="20.583">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.354">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.58">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.179">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.184">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="30.882">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="31.618">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.442">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="25.398">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.155">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="23.752">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="36.603">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="25.25">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="32.446">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="29.888">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="34.757">
    <failure type="java.util.MissingFormatArgumentException" message="Format specifier &amp;apos;%e&amp;apos;">
      <![CDATA[java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at com.DemoTest.Pages.WebDemoPage.LoginLockedoutUser(WebDemoPage.java:237)
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="23.807">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.815">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.942">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="54.714">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="29.945">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="23.091">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="22.758">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="27.267">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="19.036">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.41">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.976">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="21.062">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="20.258">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="38.05">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="24.052">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="24.77">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="22.231">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="34.751">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="19.486">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="25.456">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.587">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="24.415">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="28.177">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="19.122">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="36.202">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="10.487">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="17.711">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="19.029">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="18.155">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="31.091">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="34.262">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="22.796">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginLockedoutUser" time="26.849">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginLockedoutUser(WebDemoTest.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginLockedoutUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="28.559"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="29.079"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="29.447"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="29.637"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="30.149"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="30.968"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="31.329"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="33.829"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="36.384"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="49.268"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="28.166"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="35.668"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="30.157"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="34.644"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="39.098"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="37.095"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="38.085"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="38.71"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="43.182"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="31.907"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="41.948"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="25.886"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="27.245"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="28.269"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="29.707"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="41.535"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="35.72"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="42.068"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="46.518"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="26.552"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="32.252"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="28.034"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="27.514"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="31.594"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="42.582"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="34.033"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="40.825"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="31.546"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="37.597"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="42.551"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="33.941"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="35.695"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="15.541">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginPerfGlitchUser(WebDemoTest.java:91)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginPerfGlitchUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="39.501"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="27.389"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="27.33"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="15.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.LoginPerfGlitchUser(WebDemoTest.java:91)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LoginPerfGlitchUser -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="26.114"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="53.342"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="38.853"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="35.019"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="LoginPerfGlitchUser" time="32.276"/>
</testsuite> <!-- Command line test -->
